name: Build and deploy Node.js app to Azure Web App - SWENG861-nms6950

on:
  push:
    branches:
      - master  # Change to 'main' if needed
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read  # Required for actions/checkout

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'  # Use 18.x or your actual version; 22.x may be too new for some packages

      - name: Build frontend
        run: |
          cd front-end
          npm install
          npm run build
          cd ..
          mkdir -p back-end/public
          cp -r front-end/dist/* back-end/public/

      - name: Install backend dependencies
        run: |
          cd back-end
          npm install

      - name: Zip backend (with frontend assets included)
        run: |
          cd back-end
          zip -r ../release.zip ./*

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: node-app
          path: release.zip

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: node-app

      - name: Unzip artifact for deployment
        run: unzip release.zip

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'SWENG861-nms6950'  # ✅ Leave as-is
          slot-name: 'Production'
          package: .  # Deploys the unzipped backend folder (which includes the built frontend)
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_3E390A6E15FE4E159D83B48A68DEF4CF }}
